### ISSUE TITLE
Works in development but not in production

### ISSUE THREAD

**Issue by SanchezQb** [liuhong1happy/react-native-wallpaper-manager#3]
This library works well in development but after I create a release build, it doesn't work

**Comment by amit2319** [comment]
`def enableProguardInReleaseBuilds = false`. This was previously set to true, that's why it wasn't working in production

**Comment by harshmewada** [comment]
you can enable proguard and add this line into proguard rules

-keep class com.cunyutech.hollyliu.reactnative.wallpaper.*
this works fine in release mode
